version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: audit_system
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: <root passwd ICa***>
      MYSQL_ROOT_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '5506:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php
    links:
      - db
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:mysql
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:<root passwd ICa***>
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - mysql-network
volumes:
  dbdata:
networks:
  mysql-network:
    driver: bridge

# docker compose -up
# docker compose down
# docker-compose exec db mysql -u root -p
# show databases
# localhost:8080 for phpMyAdmin
